"""Add gender field to Shoe model

Revision ID: d2a339e8a836
Revises: 
Create Date: 2025-10-14 19:47:49.875088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a339e8a836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoe', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
